name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK & Build-Tools with all licenses
        run: |
          sudo apt update
          sudo apt install -y unzip wget zip

          export ANDROID_SDK_ROOT="$HOME/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT"/{cmdline-tools/latest,platform-tools,licenses}

          # Baixa e descompacta as ferramentas de linha de comando direto em latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cli.zip
          unzip cli.zip -d "$ANDROID_SDK_ROOT"/cmdline-tools/latest
          rm cli.zip

          # Insere as licenças necessárias
          cat > "$ANDROID_SDK_ROOT"/licenses/android-sdk-license <<EOF
          8933bad161af4178b1185d1a37fbf41ea5269c55
          d56f5187479451eabf01fb78af6dfcb131a6481e
          24333f8a63b6825ea9c5514f83c2829b004d1fee
          84831b9409646a918e30573bab4c9c91346d8abd
          EOF

          # Atualiza o PATH para incluir sdkmanager e platform-tools
          export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools"

          # Instala platform-tools, platforms e build-tools (31 e 36)
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0" \
            "build-tools;36.0.0"

      - name: Install Python & Buildozer
        run: |
          sudo apt install -y python3-pip python3-venv build-essential
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel Cython buildozer kivy

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug --quiet

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnakeChase-APK
          path: bin/snakechase-1.0-debug.apk

