name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv build-essential \
            libsdl2-dev libgles2-mesa-dev libgl1-mesa-dev \
            libgstreamer1.0-dev gstreamer1.0-plugins-{base,good,bad,ugly}

      - name: Create Python venv & install Python deps
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel Cython buildozer kivy

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug --quiet

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SnakeChase-APK
          path: bin/snakechase-1.0-debug.apk
